//! Drawing Instructions
//!
//! Drawing instructions are generated by portrayal rules (Lua) and
//! describe how to render features. These are then processed by
//! the render backend (wgpu).
//!
//! Based on S-100 standard: S100_PointInstruction, S100_LineInstruction, etc.

use crate::Color;
use serde::{Deserialize, Serialize};

/// Screen coordinate (in pixels)
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct ScreenPoint {
    pub x: f32,
    pub y: f32,
}

impl ScreenPoint {
    #[inline]
    pub fn new(x: f32, y: f32) -> Self {
        ScreenPoint { x, y }
    }

    #[inline]
    pub fn zero() -> Self {
        ScreenPoint { x: 0.0, y: 0.0 }
    }
}

/// World coordinate (in geographic units, typically degrees)
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct WorldPoint {
    pub x: f64, // Longitude
    pub y: f64, // Latitude
}

impl WorldPoint {
    #[inline]
    pub fn new(x: f64, y: f64) -> Self {
        WorldPoint { x, y }
    }
}

impl From<ferrite_s100_core::Coordinate> for WorldPoint {
    fn from(coord: ferrite_s100_core::Coordinate) -> Self {
        WorldPoint::new(coord.x, coord.y)
    }
}

/// Display priority (higher = rendered later/on top)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct DisplayPriority(pub i32);

impl Default for DisplayPriority {
    fn default() -> Self {
        DisplayPriority(5) // Default S-52 priority
    }
}

/// Geometry type for S-101 rendering order
/// Within the same priority: Area -> Line -> Point -> Text
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum GeometryType {
    Area = 0,
    Line = 1,
    Point = 2,
    Text = 3,
}

/// S-101 compliant render order key
/// Sorts by: (1) display priority, (2) render category, (3) geometry type,
/// (4) negative extent. Lower values rendered first (background).
///
/// `render_category` ensures that at the same priority, water/depth features
/// (VG 13xxx) are drawn before land features (VG 12xxx). This follows the
/// S-52 painter's algorithm where sea areas are drawn before land areas.
///
/// For area features, `neg_extent` is the negative bounding box area so that
/// larger polygons sort first (drawn as background).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct RenderOrder {
    pub priority: i32,
    /// 0 = water/depth (VG 13xxx), 1 = land (VG 12xxx), 2 = everything else
    pub render_category: i32,
    pub geometry_type: GeometryType,
    /// Negative bbox extent (larger areas → more negative → drawn first)
    pub neg_extent: i64,
}

impl RenderOrder {
    pub fn new(
        priority: DisplayPriority,
        geometry_type: GeometryType,
        _feature_id: Option<i64>,
    ) -> Self {
        RenderOrder {
            priority: priority.0,
            render_category: 2,
            geometry_type,
            neg_extent: 0,
        }
    }

    pub fn with_render_category(mut self, viewing_group: u32) -> Self {
        // S-101 viewing group classification:
        // 13xxx = depth/water features (drawn first at same priority)
        // 12xxx = land features (drawn after water at same priority)
        let vg_class = viewing_group / 10000;
        self.render_category = match vg_class {
            1 => {
                let sub = (viewing_group / 1000) % 10;
                if sub == 3 {
                    0
                }
                // 13xxx = depth/water
                else if sub == 2 {
                    1
                }
                // 12xxx = land
                else {
                    2
                }
            }
            _ => 2,
        };
        self
    }

    pub fn with_extent(mut self, extent: f64) -> Self {
        // Convert to negative integer (larger area → more negative → sorts first)
        // Scale by 1e10 to preserve precision for geographic coordinates
        self.neg_extent = -(extent * 1e10) as i64;
        self
    }
}

/// Display plane for radar overlay separation (S-100 Part 9-11.1.5)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum DisplayPlane {
    #[default]
    UnderRadar,
    OverRadar,
}

/// Scale-dependent visibility (S-100 Part 9a ScaleMinimum/ScaleMaximum)
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize)]
pub struct ScaleRange {
    /// Scale denominator below which the instruction is hidden (zoomed out too far)
    pub scale_minimum: Option<u32>,
    /// Scale denominator above which the instruction is hidden (zoomed in too far)
    pub scale_maximum: Option<u32>,
}

impl ScaleRange {
    /// Check if this instruction should be visible at the given viewing scale denominator
    #[inline]
    pub fn is_visible_at(&self, viewing_scale: u32) -> bool {
        if let Some(min) = self.scale_minimum {
            if viewing_scale > min {
                return false;
            }
        }
        if let Some(max) = self.scale_maximum {
            if viewing_scale < max {
                return false;
            }
        }
        true
    }
}

/// Viewing group for display control
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ViewingGroup(pub u32);

impl Default for ViewingGroup {
    fn default() -> Self {
        ViewingGroup(21010) // DISPLBASE - always displayed
    }
}

/// Text horizontal alignment
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum HAlign {
    #[default]
    Left,
    Center,
    Right,
}

/// Text vertical alignment
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum VAlign {
    Top,
    #[default]
    Middle,
    Bottom,
}

/// Cap style for line ends
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum CapStyle {
    #[default]
    Butt,
    Round,
    Square,
}

/// Join style for line corners
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum JoinStyle {
    #[default]
    Miter,
    Round,
    Bevel,
}

/// Point instruction - renders a symbol at a position
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PointInstruction {
    /// Symbol reference ID (from Portrayal Catalogue)
    pub symbol_ref: String,
    /// Position in world coordinates
    pub position: WorldPoint,
    /// Rotation angle in degrees (clockwise from north)
    pub rotation: f32,
    /// Scale factor
    pub scale: f32,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Scale-dependent visibility range
    pub scale_range: ScaleRange,
    /// Display plane (UnderRadar or OverRadar)
    pub display_plane: DisplayPlane,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
    /// Cell index this instruction belongs to (for multi-cell hit testing)
    /// Using u32 to save 8 bytes per instruction (Option<u32>=8 vs Option<usize>=16)
    pub cell_index: Option<u32>,
    /// Sounding depth value (meters) - for sounding symbols only
    /// Used to select the shallowest sounding when decluttering
    /// NaN = no depth (saves 8 bytes vs Option<f64>)
    depth: f64,
}

impl PointInstruction {
    #[inline]
    pub fn new(symbol_ref: String, position: WorldPoint) -> Self {
        PointInstruction {
            symbol_ref,
            position,
            rotation: 0.0,
            scale: 1.0,
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            scale_range: ScaleRange::default(),
            display_plane: DisplayPlane::default(),
            feature_id: None,
            cell_index: None,
            depth: f64::NAN,
        }
    }

    /// Get depth value if present (non-NaN)
    #[inline]
    pub fn depth(&self) -> Option<f64> {
        if self.depth.is_nan() {
            None
        } else {
            Some(self.depth)
        }
    }

    /// Check if instruction has depth value
    #[inline]
    pub fn has_depth(&self) -> bool {
        !self.depth.is_nan()
    }

    #[inline]
    pub fn with_depth(mut self, depth: f64) -> Self {
        self.depth = depth;
        self
    }

    #[inline]
    pub fn with_rotation(mut self, degrees: f32) -> Self {
        self.rotation = degrees;
        self
    }

    #[inline]
    pub fn with_scale(mut self, scale: f32) -> Self {
        self.scale = scale;
        self
    }

    #[inline]
    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    #[inline]
    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self
    }

    #[inline]
    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }

    #[inline]
    pub fn with_cell_index(mut self, index: usize) -> Self {
        self.cell_index = Some(index as u32);
        self
    }

    #[inline]
    pub fn with_scale_range(mut self, scale_range: ScaleRange) -> Self {
        self.scale_range = scale_range;
        self
    }

    #[inline]
    pub fn with_display_plane(mut self, display_plane: DisplayPlane) -> Self {
        self.display_plane = display_plane;
        self
    }
}

/// Line style definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LineStyle {
    /// Color
    pub color: Color,
    /// Color token for profile remapping (e.g., "CSTLN", "DEPVS")
    pub color_token: Option<String>,
    /// Width in pixels at nominal scale
    pub width: f32,
    /// Dash pattern (alternating on/off lengths)
    pub dash_pattern: Vec<f32>,
    /// Cap style
    pub cap: CapStyle,
    /// Join style
    pub join: JoinStyle,
}

impl Default for LineStyle {
    fn default() -> Self {
        LineStyle {
            color: Color::BLACK,
            color_token: None,
            width: 1.0,
            dash_pattern: Vec::new(),
            cap: CapStyle::Butt,
            join: JoinStyle::Miter,
        }
    }
}

impl LineStyle {
    pub fn solid(color: Color, width: f32) -> Self {
        LineStyle {
            color,
            color_token: None,
            width,
            dash_pattern: Vec::new(),
            cap: CapStyle::Butt,
            join: JoinStyle::Miter,
        }
    }

    pub fn dashed(color: Color, width: f32, pattern: Vec<f32>) -> Self {
        LineStyle {
            color,
            color_token: None,
            width,
            dash_pattern: pattern,
            cap: CapStyle::Butt,
            join: JoinStyle::Miter,
        }
    }
}

/// Line instruction - renders a line/polyline
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LineInstruction {
    /// Line style reference ID (from PC) or inline style
    pub style_ref: Option<String>,
    /// Inline style (used if style_ref is None)
    pub style: LineStyle,
    /// Color token for line color remapping
    pub color_token: Option<String>,
    /// Line vertices in world coordinates
    pub points: Vec<WorldPoint>,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Scale-dependent visibility range
    pub scale_range: ScaleRange,
    /// Display plane (UnderRadar or OverRadar)
    pub display_plane: DisplayPlane,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
    /// S-100 Part 9-11.1.9: When true (default), this line CAN be suppressed by
    /// higher-priority lines sharing the same curve geometry.
    /// LineInstructionUnsuppressed sets this to false.
    pub suppressible: bool,
}

impl LineInstruction {
    #[inline]
    pub fn new(points: Vec<WorldPoint>) -> Self {
        LineInstruction {
            style_ref: None,
            style: LineStyle::default(),
            color_token: None,
            points,
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            scale_range: ScaleRange::default(),
            display_plane: DisplayPlane::default(),
            feature_id: None,
            suppressible: true,
        }
    }

    /// Mark this line as unsuppressible (S-100 LineInstructionUnsuppressed).
    /// Unsuppressed lines always render regardless of higher-priority lines
    /// on the same curve.
    #[inline]
    pub fn with_unsuppressed(mut self) -> Self {
        self.suppressible = false;
        self
    }

    #[inline]
    pub fn with_style_ref(mut self, style_ref: String) -> Self {
        self.style_ref = Some(style_ref);
        self
    }

    #[inline]
    pub fn with_style(mut self, style: LineStyle) -> Self {
        self.style = style;
        self
    }

    #[inline]
    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    #[inline]
    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self
    }

    #[inline]
    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }

    #[inline]
    pub fn with_scale_range(mut self, scale_range: ScaleRange) -> Self {
        self.scale_range = scale_range;
        self
    }

    #[inline]
    pub fn with_display_plane(mut self, display_plane: DisplayPlane) -> Self {
        self.display_plane = display_plane;
        self
    }
}

/// Area fill type
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AreaFillType {
    /// Solid color fill
    Solid(Color),
    /// Pattern fill (symbol reference) with parallelogram tiling vectors
    /// v1 and v2 define the lattice: each symbol is at origin + n*v1 + m*v2 (in mm)
    Pattern {
        symbol_ref: String,
        /// First lattice vector (mm). v1.y is always 0 in S-101 catalogues.
        v1: (f32, f32),
        /// Second lattice vector (mm). May have non-zero x for parallelogram tiling.
        v2: (f32, f32),
    },
    /// Hatch fill: parallel lines at a given angle (S-100 Part 9a)
    HatchFill {
        /// Line color
        color: Color,
        /// Line width in mm
        width: f32,
        /// Distance between parallel lines in mm
        spacing: f32,
        /// Direction angle in degrees (from the direction vector)
        angle: f32,
    },
    /// Centroid symbol only
    CentroidSymbol(String),
}

impl Default for AreaFillType {
    fn default() -> Self {
        AreaFillType::Solid(Color::TRANSPARENT)
    }
}

/// Area instruction - renders a filled polygon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AreaInstruction {
    /// Fill style reference ID (from PC) or inline fill
    pub fill_ref: Option<String>,
    /// Fill type
    pub fill: AreaFillType,
    /// Color token for solid fill remapping (e.g., "DEPVS", "LANDA")
    pub fill_color_token: Option<String>,
    /// Color token for hatch fill line color
    pub hatch_color_token: Option<String>,
    /// Exterior ring vertices
    pub exterior: Vec<WorldPoint>,
    /// Interior rings (holes)
    pub interiors: Vec<Vec<WorldPoint>>,
    /// Optional outline
    pub outline: Option<LineStyle>,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Scale-dependent visibility range
    pub scale_range: ScaleRange,
    /// Display plane (UnderRadar or OverRadar)
    pub display_plane: DisplayPlane,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
}

impl AreaInstruction {
    #[inline]
    pub fn new(exterior: Vec<WorldPoint>) -> Self {
        AreaInstruction {
            fill_ref: None,
            fill: AreaFillType::default(),
            fill_color_token: None,
            hatch_color_token: None,
            exterior,
            interiors: Vec::new(),
            outline: None,
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            scale_range: ScaleRange::default(),
            display_plane: DisplayPlane::default(),
            feature_id: None,
        }
    }

    #[inline]
    pub fn with_fill_ref(mut self, fill_ref: String) -> Self {
        self.fill_ref = Some(fill_ref);
        self
    }

    #[inline]
    pub fn with_solid_fill(mut self, color: Color) -> Self {
        self.fill = AreaFillType::Solid(color);
        self
    }

    #[inline]
    pub fn with_solid_fill_token(mut self, color: Color, token: &str) -> Self {
        self.fill = AreaFillType::Solid(color);
        self.fill_color_token = Some(token.to_string());
        self
    }

    #[inline]
    pub fn with_pattern_fill(mut self, symbol_ref: String, v1: (f32, f32), v2: (f32, f32)) -> Self {
        self.fill = AreaFillType::Pattern { symbol_ref, v1, v2 };
        self
    }

    #[inline]
    pub fn with_hatch_fill(mut self, color: Color, width: f32, spacing: f32, angle: f32) -> Self {
        self.fill = AreaFillType::HatchFill {
            color,
            width,
            spacing,
            angle,
        };
        self
    }

    #[inline]
    pub fn with_hatch_fill_token(
        mut self,
        color: Color,
        token: &str,
        width: f32,
        spacing: f32,
        angle: f32,
    ) -> Self {
        self.fill = AreaFillType::HatchFill {
            color,
            width,
            spacing,
            angle,
        };
        self.hatch_color_token = Some(token.to_string());
        self
    }

    #[inline]
    pub fn with_interiors(mut self, interiors: Vec<Vec<WorldPoint>>) -> Self {
        self.interiors = interiors;
        self
    }

    #[inline]
    pub fn with_outline(mut self, style: LineStyle) -> Self {
        self.outline = Some(style);
        self
    }

    #[inline]
    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    #[inline]
    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self
    }

    #[inline]
    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }

    #[inline]
    pub fn with_scale_range(mut self, scale_range: ScaleRange) -> Self {
        self.scale_range = scale_range;
        self
    }

    #[inline]
    pub fn with_display_plane(mut self, display_plane: DisplayPlane) -> Self {
        self.display_plane = display_plane;
        self
    }
}

/// Text instruction - renders text label
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TextInstruction {
    /// Text content
    pub text: String,
    /// Position in world coordinates
    pub position: WorldPoint,
    /// Font size in points
    pub font_size: f32,
    /// Font family (optional)
    pub font_family: Option<String>,
    /// Font weight (bold)
    pub bold: bool,
    /// Font style (italic)
    pub italic: bool,
    /// Text color
    pub color: Color,
    /// Color token for text color remapping
    pub color_token: Option<String>,
    /// Background color (None = transparent)
    pub background: Option<Color>,
    /// Horizontal alignment
    pub h_align: HAlign,
    /// Vertical alignment
    pub v_align: VAlign,
    /// Rotation angle in degrees
    pub rotation: f32,
    /// Offset from position (in screen pixels)
    pub offset: ScreenPoint,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Scale-dependent visibility range
    pub scale_range: ScaleRange,
    /// Display plane (UnderRadar or OverRadar)
    pub display_plane: DisplayPlane,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
}

impl TextInstruction {
    #[inline]
    pub fn new(text: String, position: WorldPoint) -> Self {
        TextInstruction {
            text,
            position,
            font_size: 10.0,
            font_family: None,
            bold: false,
            italic: false,
            color: Color::BLACK,
            background: None,
            h_align: HAlign::Left,
            v_align: VAlign::Middle,
            rotation: 0.0,
            offset: ScreenPoint::zero(),
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            scale_range: ScaleRange::default(),
            display_plane: DisplayPlane::default(),
            feature_id: None,
            color_token: None,
        }
    }

    #[inline]
    pub fn with_font_size(mut self, size: f32) -> Self {
        self.font_size = size;
        self
    }

    #[inline]
    pub fn with_color(mut self, color: Color) -> Self {
        self.color = color;
        self
    }

    #[inline]
    pub fn with_alignment(mut self, h: HAlign, v: VAlign) -> Self {
        self.h_align = h;
        self.v_align = v;
        self
    }

    #[inline]
    pub fn with_rotation(mut self, degrees: f32) -> Self {
        self.rotation = degrees;
        self
    }

    #[inline]
    pub fn with_offset(mut self, x: f32, y: f32) -> Self {
        self.offset = ScreenPoint::new(x, y);
        self
    }

    #[inline]
    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    #[inline]
    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self
    }

    #[inline]
    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }

    #[inline]
    pub fn with_scale_range(mut self, scale_range: ScaleRange) -> Self {
        self.scale_range = scale_range;
        self
    }

    #[inline]
    pub fn with_display_plane(mut self, display_plane: DisplayPlane) -> Self {
        self.display_plane = display_plane;
        self
    }
}

/// All drawing instruction types
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DrawingInstruction {
    Point(PointInstruction),
    Line(LineInstruction),
    Area(AreaInstruction),
    Text(TextInstruction),
}

impl DrawingInstruction {
    pub fn priority(&self) -> DisplayPriority {
        match self {
            DrawingInstruction::Point(i) => i.priority,
            DrawingInstruction::Line(i) => i.priority,
            DrawingInstruction::Area(i) => i.priority,
            DrawingInstruction::Text(i) => i.priority,
        }
    }

    pub fn viewing_group(&self) -> ViewingGroup {
        match self {
            DrawingInstruction::Point(i) => i.viewing_group,
            DrawingInstruction::Line(i) => i.viewing_group,
            DrawingInstruction::Area(i) => i.viewing_group,
            DrawingInstruction::Text(i) => i.viewing_group,
        }
    }

    pub fn feature_id(&self) -> Option<i64> {
        match self {
            DrawingInstruction::Point(i) => i.feature_id,
            DrawingInstruction::Line(i) => i.feature_id,
            DrawingInstruction::Area(i) => i.feature_id,
            DrawingInstruction::Text(i) => i.feature_id,
        }
    }

    pub fn scale_range(&self) -> ScaleRange {
        match self {
            DrawingInstruction::Point(i) => i.scale_range,
            DrawingInstruction::Line(i) => i.scale_range,
            DrawingInstruction::Area(i) => i.scale_range,
            DrawingInstruction::Text(i) => i.scale_range,
        }
    }

    pub fn display_plane(&self) -> DisplayPlane {
        match self {
            DrawingInstruction::Point(i) => i.display_plane,
            DrawingInstruction::Line(i) => i.display_plane,
            DrawingInstruction::Area(i) => i.display_plane,
            DrawingInstruction::Text(i) => i.display_plane,
        }
    }

    /// Get geometry type for S-101 render ordering
    pub fn geometry_type(&self) -> GeometryType {
        match self {
            DrawingInstruction::Area(_) => GeometryType::Area,
            DrawingInstruction::Line(_) => GeometryType::Line,
            DrawingInstruction::Point(_) => GeometryType::Point,
            DrawingInstruction::Text(_) => GeometryType::Text,
        }
    }

    /// Get S-101 compliant render order key
    /// Used for sorting: lower values rendered first (background)
    pub fn render_order(&self) -> RenderOrder {
        let order = RenderOrder::new(self.priority(), self.geometry_type(), self.feature_id())
            .with_render_category(self.viewing_group().0);
        // For area features, sort by bounding box extent (larger areas first = background)
        if let DrawingInstruction::Area(area) = self {
            let (mut x0, mut y0, mut x1, mut y1) = (f64::MAX, f64::MAX, f64::MIN, f64::MIN);
            for p in &area.exterior {
                if p.x < x0 {
                    x0 = p.x;
                }
                if p.y < y0 {
                    y0 = p.y;
                }
                if p.x > x1 {
                    x1 = p.x;
                }
                if p.y > y1 {
                    y1 = p.y;
                }
            }
            let extent = (x1 - x0) * (y1 - y0);
            return order.with_extent(extent);
        }
        order
    }

    /// Remap resolved colors using a token-to-color lookup function.
    /// Used for color profile switch (Day/Dusk/Night) without re-running Lua.
    pub fn remap_colors(&mut self, lookup: &dyn Fn(&str) -> Color) {
        match self {
            DrawingInstruction::Area(area) => {
                if let Some(token) = &area.fill_color_token {
                    if let AreaFillType::Solid(ref mut color) = area.fill {
                        *color = lookup(token);
                    }
                }
                if let Some(token) = &area.hatch_color_token {
                    if let AreaFillType::HatchFill { ref mut color, .. } = area.fill {
                        *color = lookup(token);
                    }
                }
                if let Some(ref mut outline) = area.outline {
                    if let Some(token) = &outline.color_token {
                        outline.color = lookup(token);
                    }
                }
            }
            DrawingInstruction::Line(line) => {
                if let Some(token) = &line.color_token {
                    line.style.color = lookup(token);
                }
            }
            DrawingInstruction::Text(text) => {
                if let Some(token) = &text.color_token {
                    text.color = lookup(token);
                }
            }
            DrawingInstruction::Point(_) => {
                // Point symbols use SVG rendering with color overrides;
                // handled by clearing symbol_cache on profile switch
            }
        }
    }
}

/// Collection of drawing instructions for a feature
#[derive(Debug, Clone, Default)]
pub struct FeatureInstructions {
    pub instructions: Vec<DrawingInstruction>,
}

impl FeatureInstructions {
    pub fn new() -> Self {
        FeatureInstructions {
            instructions: Vec::new(),
        }
    }

    pub fn add_point(&mut self, instruction: PointInstruction) {
        self.instructions
            .push(DrawingInstruction::Point(instruction));
    }

    pub fn add_line(&mut self, instruction: LineInstruction) {
        self.instructions
            .push(DrawingInstruction::Line(instruction));
    }

    pub fn add_area(&mut self, instruction: AreaInstruction) {
        self.instructions
            .push(DrawingInstruction::Area(instruction));
    }

    pub fn add_text(&mut self, instruction: TextInstruction) {
        self.instructions
            .push(DrawingInstruction::Text(instruction));
    }

    pub fn is_empty(&self) -> bool {
        self.instructions.is_empty()
    }

    pub fn len(&self) -> usize {
        self.instructions.len()
    }

    /// Sort by display priority
    pub fn sort_by_priority(&mut self) {
        self.instructions.sort_by_key(|i| i.priority());
    }
}
