//! Drawing Instructions
//!
//! Drawing instructions are generated by portrayal rules (Lua) and
//! describe how to render features. These are then processed by
//! the render backend (wgpu).
//!
//! Based on S-100 standard: S100_PointInstruction, S100_LineInstruction, etc.

use crate::Color;

/// Screen coordinate (in pixels)
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ScreenPoint {
    pub x: f32,
    pub y: f32,
}

impl ScreenPoint {
    #[inline]
    pub fn new(x: f32, y: f32) -> Self {
        ScreenPoint { x, y }
    }

    #[inline]
    pub fn zero() -> Self {
        ScreenPoint { x: 0.0, y: 0.0 }
    }
}

/// World coordinate (in geographic units, typically degrees)
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct WorldPoint {
    pub x: f64, // Longitude
    pub y: f64, // Latitude
}

impl WorldPoint {
    #[inline]
    pub fn new(x: f64, y: f64) -> Self {
        WorldPoint { x, y }
    }
}

impl From<ferrite_s100_core::Coordinate> for WorldPoint {
    fn from(coord: ferrite_s100_core::Coordinate) -> Self {
        WorldPoint::new(coord.x, coord.y)
    }
}

/// Display priority (higher = rendered later/on top)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct DisplayPriority(pub i32);

impl Default for DisplayPriority {
    fn default() -> Self {
        DisplayPriority(5) // Default S-52 priority
    }
}

/// Viewing group for display control
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ViewingGroup(pub u32);

impl Default for ViewingGroup {
    fn default() -> Self {
        ViewingGroup(21010) // DISPLBASE - always displayed
    }
}

/// Text horizontal alignment
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum HAlign {
    #[default]
    Left,
    Center,
    Right,
}

/// Text vertical alignment
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum VAlign {
    Top,
    #[default]
    Middle,
    Bottom,
}

/// Cap style for line ends
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CapStyle {
    #[default]
    Butt,
    Round,
    Square,
}

/// Join style for line corners
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum JoinStyle {
    #[default]
    Miter,
    Round,
    Bevel,
}

/// Point instruction - renders a symbol at a position
#[derive(Debug, Clone)]
pub struct PointInstruction {
    /// Symbol reference ID (from Portrayal Catalogue)
    pub symbol_ref: String,
    /// Position in world coordinates
    pub position: WorldPoint,
    /// Rotation angle in degrees (clockwise from north)
    pub rotation: f32,
    /// Scale factor
    pub scale: f32,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
    /// Cell index this instruction belongs to (for multi-cell hit testing)
    pub cell_index: Option<usize>,
    /// Sounding depth value (meters) - for sounding symbols only
    /// Used to select the shallowest sounding when decluttering
    pub depth: Option<f64>,
}

impl PointInstruction {
    pub fn new(symbol_ref: String, position: WorldPoint) -> Self {
        PointInstruction {
            symbol_ref,
            position,
            rotation: 0.0,
            scale: 1.0,
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            feature_id: None,
            cell_index: None,
            depth: None,
        }
    }

    pub fn with_depth(mut self, depth: f64) -> Self {
        self.depth = Some(depth);
        self
    }

    pub fn with_rotation(mut self, degrees: f32) -> Self {
        self.rotation = degrees;
        self
    }

    pub fn with_scale(mut self, scale: f32) -> Self {
        self.scale = scale;
        self
    }

    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self
    }

    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }

    pub fn with_cell_index(mut self, index: usize) -> Self {
        self.cell_index = Some(index);
        self
    }
}

/// Line style definition
#[derive(Debug, Clone)]
pub struct LineStyle {
    /// Color
    pub color: Color,
    /// Width in pixels at nominal scale
    pub width: f32,
    /// Dash pattern (alternating on/off lengths)
    pub dash_pattern: Vec<f32>,
    /// Cap style
    pub cap: CapStyle,
    /// Join style
    pub join: JoinStyle,
}

impl Default for LineStyle {
    fn default() -> Self {
        LineStyle {
            color: Color::BLACK,
            width: 1.0,
            dash_pattern: Vec::new(),
            cap: CapStyle::Butt,
            join: JoinStyle::Miter,
        }
    }
}

impl LineStyle {
    pub fn solid(color: Color, width: f32) -> Self {
        LineStyle {
            color,
            width,
            dash_pattern: Vec::new(),
            cap: CapStyle::Butt,
            join: JoinStyle::Miter,
        }
    }

    pub fn dashed(color: Color, width: f32, pattern: Vec<f32>) -> Self {
        LineStyle {
            color,
            width,
            dash_pattern: pattern,
            cap: CapStyle::Butt,
            join: JoinStyle::Miter,
        }
    }
}

/// Line instruction - renders a line/polyline
#[derive(Debug, Clone)]
pub struct LineInstruction {
    /// Line style reference ID (from PC) or inline style
    pub style_ref: Option<String>,
    /// Inline style (used if style_ref is None)
    pub style: LineStyle,
    /// Line vertices in world coordinates
    pub points: Vec<WorldPoint>,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
}

impl LineInstruction {
    pub fn new(points: Vec<WorldPoint>) -> Self {
        LineInstruction {
            style_ref: None,
            style: LineStyle::default(),
            points,
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            feature_id: None,
        }
    }

    pub fn with_style_ref(mut self, style_ref: String) -> Self {
        self.style_ref = Some(style_ref);
        self
    }

    pub fn with_style(mut self, style: LineStyle) -> Self {
        self.style = style;
        self
    }

    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self
    }

    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }
}

/// Area fill type
#[derive(Debug, Clone)]
pub enum AreaFillType {
    /// Solid color fill
    Solid(Color),
    /// Pattern fill (symbol reference)
    Pattern {
        symbol_ref: String,
        spacing_x: f32,
        spacing_y: f32,
    },
    /// Centroid symbol only
    CentroidSymbol(String),
}

impl Default for AreaFillType {
    fn default() -> Self {
        AreaFillType::Solid(Color::TRANSPARENT)
    }
}

/// Area instruction - renders a filled polygon
#[derive(Debug, Clone)]
pub struct AreaInstruction {
    /// Fill style reference ID (from PC) or inline fill
    pub fill_ref: Option<String>,
    /// Fill type
    pub fill: AreaFillType,
    /// Exterior ring vertices
    pub exterior: Vec<WorldPoint>,
    /// Interior rings (holes)
    pub interiors: Vec<Vec<WorldPoint>>,
    /// Optional outline
    pub outline: Option<LineStyle>,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
}

impl AreaInstruction {
    pub fn new(exterior: Vec<WorldPoint>) -> Self {
        AreaInstruction {
            fill_ref: None,
            fill: AreaFillType::default(),
            exterior,
            interiors: Vec::new(),
            outline: None,
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            feature_id: None,
        }
    }

    pub fn with_fill_ref(mut self, fill_ref: String) -> Self {
        self.fill_ref = Some(fill_ref);
        self
    }

    pub fn with_solid_fill(mut self, color: Color) -> Self {
        self.fill = AreaFillType::Solid(color);
        self
    }

    pub fn with_pattern_fill(mut self, symbol_ref: String, spacing_x: f32, spacing_y: f32) -> Self {
        self.fill = AreaFillType::Pattern {
            symbol_ref,
            spacing_x,
            spacing_y,
        };
        self
    }

    pub fn with_interiors(mut self, interiors: Vec<Vec<WorldPoint>>) -> Self {
        self.interiors = interiors;
        self
    }

    pub fn with_outline(mut self, style: LineStyle) -> Self {
        self.outline = Some(style);
        self
    }

    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self
    }

    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }
}

/// Text instruction - renders text label
#[derive(Debug, Clone)]
pub struct TextInstruction {
    /// Text content
    pub text: String,
    /// Position in world coordinates
    pub position: WorldPoint,
    /// Font size in points
    pub font_size: f32,
    /// Font family (optional)
    pub font_family: Option<String>,
    /// Font weight (bold)
    pub bold: bool,
    /// Font style (italic)
    pub italic: bool,
    /// Text color
    pub color: Color,
    /// Background color (None = transparent)
    pub background: Option<Color>,
    /// Horizontal alignment
    pub h_align: HAlign,
    /// Vertical alignment
    pub v_align: VAlign,
    /// Rotation angle in degrees
    pub rotation: f32,
    /// Offset from position (in screen pixels)
    pub offset: ScreenPoint,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
}

impl TextInstruction {
    pub fn new(text: String, position: WorldPoint) -> Self {
        TextInstruction {
            text,
            position,
            font_size: 10.0,
            font_family: None,
            bold: false,
            italic: false,
            color: Color::BLACK,
            background: None,
            h_align: HAlign::Left,
            v_align: VAlign::Middle,
            rotation: 0.0,
            offset: ScreenPoint::zero(),
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            feature_id: None,
        }
    }

    pub fn with_font_size(mut self, size: f32) -> Self {
        self.font_size = size;
        self
    }

    pub fn with_color(mut self, color: Color) -> Self {
        self.color = color;
        self
    }

    pub fn with_alignment(mut self, h: HAlign, v: VAlign) -> Self {
        self.h_align = h;
        self.v_align = v;
        self
    }

    pub fn with_rotation(mut self, degrees: f32) -> Self {
        self.rotation = degrees;
        self
    }

    pub fn with_offset(mut self, x: f32, y: f32) -> Self {
        self.offset = ScreenPoint::new(x, y);
        self
    }

    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self
    }

    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }
}

/// All drawing instruction types
#[derive(Debug, Clone)]
pub enum DrawingInstruction {
    Point(PointInstruction),
    Line(LineInstruction),
    Area(AreaInstruction),
    Text(TextInstruction),
}

impl DrawingInstruction {
    pub fn priority(&self) -> DisplayPriority {
        match self {
            DrawingInstruction::Point(i) => i.priority,
            DrawingInstruction::Line(i) => i.priority,
            DrawingInstruction::Area(i) => i.priority,
            DrawingInstruction::Text(i) => i.priority,
        }
    }

    pub fn viewing_group(&self) -> ViewingGroup {
        match self {
            DrawingInstruction::Point(i) => i.viewing_group,
            DrawingInstruction::Line(i) => i.viewing_group,
            DrawingInstruction::Area(i) => i.viewing_group,
            DrawingInstruction::Text(i) => i.viewing_group,
        }
    }

    pub fn feature_id(&self) -> Option<i64> {
        match self {
            DrawingInstruction::Point(i) => i.feature_id,
            DrawingInstruction::Line(i) => i.feature_id,
            DrawingInstruction::Area(i) => i.feature_id,
            DrawingInstruction::Text(i) => i.feature_id,
        }
    }
}

/// Collection of drawing instructions for a feature
#[derive(Debug, Clone, Default)]
pub struct FeatureInstructions {
    pub instructions: Vec<DrawingInstruction>,
}

impl FeatureInstructions {
    pub fn new() -> Self {
        FeatureInstructions {
            instructions: Vec::new(),
        }
    }

    pub fn add_point(&mut self, instruction: PointInstruction) {
        self.instructions
            .push(DrawingInstruction::Point(instruction));
    }

    pub fn add_line(&mut self, instruction: LineInstruction) {
        self.instructions
            .push(DrawingInstruction::Line(instruction));
    }

    pub fn add_area(&mut self, instruction: AreaInstruction) {
        self.instructions
            .push(DrawingInstruction::Area(instruction));
    }

    pub fn add_text(&mut self, instruction: TextInstruction) {
        self.instructions
            .push(DrawingInstruction::Text(instruction));
    }

    pub fn is_empty(&self) -> bool {
        self.instructions.is_empty()
    }

    pub fn len(&self) -> usize {
        self.instructions.len()
    }

    /// Sort by display priority
    pub fn sort_by_priority(&mut self) {
        self.instructions.sort_by_key(|i| i.priority());
    }
}
