//! Drawing Instructions
//!
//! Drawing instructions are generated by portrayal rules (Lua) and
//! describe how to render features. These are then processed by
//! the render backend (wgpu).
//!
//! Based on S-100 standard: S100_PointInstruction, S100_LineInstruction, etc.

use crate::Color;
use serde::{Deserialize, Serialize};

/// Screen coordinate (in pixels)
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct ScreenPoint {
    pub x: f32,
    pub y: f32,
}

impl ScreenPoint {
    #[inline]
    pub fn new(x: f32, y: f32) -> Self {
        ScreenPoint { x, y }
    }

    #[inline]
    pub fn zero() -> Self {
        ScreenPoint { x: 0.0, y: 0.0 }
    }
}

/// World coordinate (in geographic units, typically degrees)
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct WorldPoint {
    pub x: f64, // Longitude
    pub y: f64, // Latitude
}

impl WorldPoint {
    #[inline]
    pub fn new(x: f64, y: f64) -> Self {
        WorldPoint { x, y }
    }
}

impl From<ferrite_s100_core::Coordinate> for WorldPoint {
    fn from(coord: ferrite_s100_core::Coordinate) -> Self {
        WorldPoint::new(coord.x, coord.y)
    }
}

/// Display priority (higher = rendered later/on top)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct DisplayPriority(pub i32);

impl Default for DisplayPriority {
    fn default() -> Self {
        DisplayPriority(5) // Default S-52 priority
    }
}

/// Geometry type for S-101 rendering order
/// Within the same priority: Area -> Line -> Point -> Text
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum GeometryType {
    Area = 0,
    Line = 1,
    Point = 2,
    Text = 3,
}

/// S-101 compliant render order key
/// Sorts by: (1) display priority, (2) render category, (3) geometry type,
/// (4) negative extent. Lower values rendered first (background).
///
/// `render_category` ensures that at the same priority, water/depth features
/// (VG 13xxx) are drawn before land features (VG 12xxx). This follows the
/// S-52 painter's algorithm where sea areas are drawn before land areas.
///
/// For area features, `neg_extent` is the negative bounding box area so that
/// larger polygons sort first (drawn as background).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct RenderOrder {
    pub priority: i32,
    /// 0 = water/depth (VG 13xxx), 1 = land (VG 12xxx), 2 = everything else
    pub render_category: i32,
    pub geometry_type: GeometryType,
    /// Negative bbox extent (larger areas → more negative → drawn first)
    pub neg_extent: i64,
}

impl RenderOrder {
    pub fn new(
        priority: DisplayPriority,
        geometry_type: GeometryType,
        _feature_id: Option<i64>,
    ) -> Self {
        RenderOrder {
            priority: priority.0,
            render_category: 2,
            geometry_type,
            neg_extent: 0,
        }
    }

    pub fn with_render_category(mut self, viewing_group: u32) -> Self {
        // S-101 viewing group classification:
        // 13xxx = depth/water features (drawn first at same priority)
        // 12xxx = land features (drawn after water at same priority)
        let vg_class = viewing_group / 10000;
        self.render_category = match vg_class {
            1 => {
                let sub = (viewing_group / 1000) % 10;
                if sub == 3 {
                    0
                }
                // 13xxx = depth/water
                else if sub == 2 {
                    1
                }
                // 12xxx = land
                else {
                    2
                }
            }
            _ => 2,
        };
        self
    }

    pub fn with_extent(mut self, extent: f64) -> Self {
        // Convert to negative integer (larger area → more negative → sorts first)
        // Scale by 1e10 to preserve precision for geographic coordinates
        self.neg_extent = -(extent * 1e10) as i64;
        self
    }
}

/// Display plane for radar overlay separation (S-100 Part 9-11.1.5)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum DisplayPlane {
    #[default]
    UnderRadar,
    OverRadar,
    /// Display-plane order supplied by an Interoperability Catalogue.
    /// Negative is below radar, positive above; zero cannot be decoded.
    Interoperability(std::num::NonZeroI32),
    /// Display-plane order declared by a product Portrayal Catalogue.
    Catalogue(std::num::NonZeroI32),
}
impl DisplayPlane {
    pub fn from_catalogue_order(order: std::num::NonZeroI32) -> Self {
        match order.get() {
            -1 => Self::UnderRadar,
            1 => Self::OverRadar,
            _ => Self::Catalogue(order),
        }
    }
    pub fn order(self) -> std::num::NonZeroI32 {
        match self {
            Self::UnderRadar => std::num::NonZeroI32::new(-1).unwrap(),
            Self::OverRadar => std::num::NonZeroI32::new(1).unwrap(),
            Self::Interoperability(order) | Self::Catalogue(order) => order,
        }
    }
    pub fn composition_plane(
        self,
        stage: ferrite_kernel::CompositionStage,
    ) -> ferrite_kernel::CompositionPlane {
        ferrite_kernel::CompositionPlane::new(stage, self.order())
    }
}

/// Scale-dependent visibility (S-100 Part 9a ScaleMinimum/ScaleMaximum)
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize)]
pub struct ScaleRange {
    /// Scale denominator above which the instruction is hidden (zoomed out too far)
    pub scale_minimum: Option<u32>,
    /// Scale denominator below which the instruction is hidden (zoomed in too far)
    pub scale_maximum: Option<u32>,
}

impl ScaleRange {
    /// Check if this instruction should be visible at the given viewing scale denominator
    #[inline]
    pub fn is_visible_at(&self, viewing_scale: u32) -> bool {
        if let Some(min) = self.scale_minimum {
            if viewing_scale > min {
                return false;
            }
        }
        if let Some(max) = self.scale_maximum {
            if viewing_scale < max {
                return false;
            }
        }
        true
    }
}

/// Viewing group for display control
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ViewingGroup(pub u32);

impl Default for ViewingGroup {
    fn default() -> Self {
        ViewingGroup(21010) // DISPLBASE - always displayed
    }
}

/// Text horizontal alignment
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum HAlign {
    #[default]
    Left,
    Center,
    Right,
}

/// Text vertical alignment
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum VAlign {
    Top,
    #[default]
    Middle,
    Bottom,
}

/// Cap style for line ends
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum CapStyle {
    #[default]
    Butt,
    Round,
    Square,
}

/// Join style for line corners
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum JoinStyle {
    #[default]
    Miter,
    Round,
    Bevel,
}

/// Point instruction - renders a symbol at a position
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PointInstruction {
    /// Symbol reference ID (from Portrayal Catalogue)
    pub symbol_ref: String,
    /// Position in world coordinates
    pub position: WorldPoint,
    /// Clockwise degrees relative to rotation_crs, not always true north.
    pub rotation: f32,
    #[serde(default)]
    pub rotation_crs: crate::RotationCrs,
    /// Bearing of the source curve tangent. Local/Line positive Y is its left normal.
    /// None for point/surface local CRS, whose axes parallel portrayal axes.
    #[serde(default)]
    pub curve_tangent_bearing: Option<f64>,
    /// Source curve and view-dependent S-100 placement; resolve at draw time.
    #[serde(default)]
    pub line_placement: Option<Box<crate::LineSymbolPlacement>>,
    /// Scale factor
    pub scale: f32,
    /// Offset in local portrayal coordinates (millimetres, positive Y upwards).
    pub local_offset: (f32, f32),
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Additional groups are conjunctive under S-100 9-11.1.3.
    #[serde(default)]
    pub additional_viewing_groups: Box<[ViewingGroup]>,
    /// Scale-dependent visibility range
    pub scale_range: ScaleRange,
    /// Display plane (UnderRadar or OverRadar)
    pub display_plane: DisplayPlane,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
    /// Cell index this instruction belongs to (for multi-cell hit testing)
    /// Using u32 to save 8 bytes per instruction (Option<u32>=8 vs Option<usize>=16)
    pub cell_index: Option<u32>,
    /// Accumulated S-100 time intervals; None means no temporal restriction.
    #[serde(default)]
    pub time_intervals: Option<Box<[ferrite_kernel::TemporalInterval]>>,
    #[serde(default)]
    pub dependency: Option<Box<crate::DrawingDependency>>,
    /// Source geometry for coverage visibility; independent of portrayal offsets.
    #[serde(default)]
    pub portrayal_origin: crate::PortrayalOrigin,
    /// Sounding depth value (meters) - for sounding symbols only
    /// Used to select the shallowest sounding when decluttering
    /// NaN = no depth (saves 8 bytes vs Option<f64>)
    depth: f64,
}

impl PointInstruction {
    #[inline]
    pub fn new(symbol_ref: String, position: WorldPoint) -> Self {
        PointInstruction {
            symbol_ref,
            position,
            rotation: 0.0,
            rotation_crs: crate::RotationCrs::Portrayal,
            curve_tangent_bearing: None,
            line_placement: None,
            scale: 1.0,
            local_offset: (0.0, 0.0),
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            additional_viewing_groups: Box::default(),
            scale_range: ScaleRange::default(),
            display_plane: DisplayPlane::default(),
            feature_id: None,
            cell_index: None,
            time_intervals: None,
            dependency: None,
            portrayal_origin: crate::PortrayalOrigin::Unspecified,
            depth: f64::NAN,
        }
    }

    /// Get depth value if present (non-NaN)
    #[inline]
    pub fn depth(&self) -> Option<f64> {
        if self.depth.is_nan() {
            None
        } else {
            Some(self.depth)
        }
    }

    /// Check if instruction has depth value
    #[inline]
    pub fn has_depth(&self) -> bool {
        !self.depth.is_nan()
    }

    #[inline]
    pub fn with_depth(mut self, depth: f64) -> Self {
        self.depth = depth;
        self
    }

    #[inline]
    pub fn with_rotation(mut self, degrees: f32) -> Self {
        self.rotation = degrees;
        self
    }

    /// Copy metadata without cloning the source path for every visible piece.
    pub fn resolved_at(&self, position: WorldPoint, curve_tangent_bearing: Option<f64>) -> Self {
        Self {
            position,
            curve_tangent_bearing,
            line_placement: None,
            symbol_ref: self.symbol_ref.clone(),
            rotation: self.rotation,
            rotation_crs: self.rotation_crs,
            scale: self.scale,
            local_offset: self.local_offset,
            priority: self.priority,
            viewing_group: self.viewing_group,
            additional_viewing_groups: self.additional_viewing_groups.clone(),
            scale_range: self.scale_range,
            display_plane: self.display_plane,
            feature_id: self.feature_id,
            cell_index: self.cell_index,
            time_intervals: self.time_intervals.clone(),
            dependency: self.dependency.clone(),
            portrayal_origin: self.portrayal_origin.clone(),
            depth: self.depth,
        }
    }
    pub fn with_line_placement(mut self, value: crate::LineSymbolPlacement) -> Self {
        self.line_placement = Some(Box::new(value));
        self
    }
    pub fn with_rotation_crs(mut self, crs: crate::RotationCrs) -> Self {
        self.rotation_crs = crs;
        self
    }
    pub fn with_curve_tangent(mut self, bearing: Option<f64>) -> Self {
        self.curve_tangent_bearing = bearing;
        self
    }

    #[inline]
    pub fn with_scale(mut self, scale: f32) -> Self {
        self.scale = scale;
        self
    }

    /// Apply S-100 LocalOffset in millimetres.
    pub fn with_offset(mut self, x: f32, y: f32) -> Self {
        self.local_offset = (x, y);
        self
    }

    #[inline]
    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    /// Preserve every PC group; a disabled additional group disables this command.
    #[inline]
    pub fn with_viewing_groups(mut self, groups: &[u32]) -> Self {
        self.viewing_group = ViewingGroup(groups.first().copied().unwrap_or(21010));
        self.additional_viewing_groups = groups.iter().skip(1).copied().map(ViewingGroup).collect();
        self
    }

    #[inline]
    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self.additional_viewing_groups = Box::default();
        self
    }

    #[inline]
    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }

    #[inline]
    pub fn with_cell_index(mut self, index: usize) -> Self {
        self.cell_index = Some(index as u32);
        self
    }

    #[inline]
    pub fn with_scale_range(mut self, scale_range: ScaleRange) -> Self {
        self.scale_range = scale_range;
        self
    }

    #[inline]
    pub fn with_display_plane(mut self, display_plane: DisplayPlane) -> Self {
        self.display_plane = display_plane;
        self
    }
}

/// Explicit screen-space units, independent of any S-100 product adapter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum StrokeUnit {
    /// Device framebuffer pixels, retained for existing programmatic instructions.
    #[default]
    PhysicalPixels,
    /// Portrayal millimetres, converted using the renderer's display metrics.
    Millimetres,
}

/// Line style definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LineStyle {
    /// Color
    pub color: Color,
    /// Color token for profile remapping (e.g., "CSTLN", "DEPVS")
    pub color_token: Option<String>,
    /// Width expressed in `width_unit`; independent of map zoom.
    pub width: f32,
    /// Authored opacity multiplier retained across colour profile changes.
    #[serde(default = "opaque_opacity")]
    pub opacity: f32,
    #[serde(default)]
    pub width_unit: StrokeUnit,
    /// Dash pattern (alternating on/off lengths)
    pub dash_pattern: Vec<f32>,
    /// Canonical S-100 repeating dash intervals in millimetres.
    #[serde(default)]
    pub dash_cycle: Option<ferrite_kernel::DashCycle>,
    /// Authored physical displacement to the left of the line direction.
    #[serde(default)]
    pub offset_mm: f64,
    #[serde(default)]
    pub interval_length_mm: f64,
    #[serde(default)]
    pub authored_symbols: Vec<ferrite_kernel::StrokeSymbol>,
    /// Cap style
    pub cap: CapStyle,
    /// Join style
    pub join: JoinStyle,
}

fn opaque_opacity() -> f32 {
    1.
}

impl Default for LineStyle {
    fn default() -> Self {
        LineStyle {
            color: Color::BLACK,
            color_token: None,
            width: 1.0,
            width_unit: StrokeUnit::PhysicalPixels,
            opacity: 1.,
            dash_pattern: Vec::new(),
            dash_cycle: None,
            offset_mm: 0.,
            interval_length_mm: 0.,
            authored_symbols: Vec::new(),
            cap: CapStyle::Butt,
            join: JoinStyle::Miter,
        }
    }
}

impl LineStyle {
    pub fn has_visible_stroke(&self) -> bool {
        self.width.is_finite() && self.width > 0. && self.color.a.is_finite() && self.color.a > 0.
    }

    pub fn solid(color: Color, width: f32) -> Self {
        LineStyle {
            color,
            color_token: None,
            width,
            width_unit: StrokeUnit::PhysicalPixels,
            opacity: 1.,
            dash_pattern: Vec::new(),
            dash_cycle: None,
            offset_mm: 0.,
            interval_length_mm: 0.,
            authored_symbols: Vec::new(),
            cap: CapStyle::Butt,
            join: JoinStyle::Miter,
        }
    }

    /// S-100 Part 9-12.2.2.4 and Part 9a PenWidth specify millimetres.
    pub fn solid_mm(color: Color, width: f32) -> Self {
        Self {
            width_unit: StrokeUnit::Millimetres,
            ..Self::solid(color, width)
        }
    }

    pub fn physical_width(&self, pixels_per_mm: f32) -> f32 {
        let width = match self.width_unit {
            StrokeUnit::PhysicalPixels => self.width,
            StrokeUnit::Millimetres => self.width * pixels_per_mm,
        };
        if width.is_finite() && width > 0.0 {
            width
        } else {
            0.0
        }
    }

    pub fn dashed(color: Color, width: f32, pattern: Vec<f32>) -> Self {
        LineStyle {
            color,
            color_token: None,
            width,
            width_unit: StrokeUnit::PhysicalPixels,
            opacity: 1.,
            dash_pattern: pattern,
            dash_cycle: None,
            offset_mm: 0.,
            interval_length_mm: 0.,
            authored_symbols: Vec::new(),
            cap: CapStyle::Butt,
            join: JoinStyle::Miter,
        }
    }
}

/// Line instruction - renders a line/polyline
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LineInstruction {
    /// Deferred fixed-size ray in portrayal/local millimetres, resolved with current display metrics.
    #[serde(default)]
    pub screen_ray: Option<ScreenRay>,
    #[serde(default)]
    pub portrayal_path: Option<crate::PortrayalPath>,
    /// Line style reference ID (from PC) or inline style
    pub style_ref: Option<String>,
    /// Inline style (used if style_ref is None)
    pub style: LineStyle,
    /// Color token for line color remapping
    pub color_token: Option<String>,
    /// Line vertices in world coordinates
    pub points: Vec<WorldPoint>,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Additional groups are conjunctive under S-100 9-11.1.3.
    #[serde(default)]
    pub additional_viewing_groups: Box<[ViewingGroup]>,
    /// Scale-dependent visibility range
    pub scale_range: ScaleRange,
    /// Display plane (UnderRadar or OverRadar)
    pub display_plane: DisplayPlane,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
    /// Source cell identity; feature IDs are only unique within a cell.
    #[serde(default)]
    pub cell_index: Option<u32>,
    /// Accumulated S-100 time intervals; None means no temporal restriction.
    #[serde(default)]
    pub time_intervals: Option<Box<[ferrite_kernel::TemporalInterval]>>,
    #[serde(default)]
    pub dependency: Option<Box<crate::DrawingDependency>>,
    /// Source geometry for coverage visibility; independent of portrayal offsets.
    #[serde(default)]
    pub portrayal_origin: crate::PortrayalOrigin,
    /// S-100 Part 9-11.1.9: When true (default), this line CAN be suppressed by
    /// higher-priority lines sharing the same curve geometry.
    /// LineInstructionUnsuppressed sets this to false.
    pub suppressible: bool,
}

impl LineInstruction {
    #[inline]
    pub fn new(points: Vec<WorldPoint>) -> Self {
        LineInstruction {
            style_ref: None,
            screen_ray: None,
            portrayal_path: None,
            style: LineStyle::default(),
            color_token: None,
            points,
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            additional_viewing_groups: Box::default(),
            scale_range: ScaleRange::default(),
            display_plane: DisplayPlane::default(),
            feature_id: None,
            cell_index: None,
            time_intervals: None,
            dependency: None,
            portrayal_origin: crate::PortrayalOrigin::Unspecified,
            suppressible: true,
        }
    }

    /// Mark this line as unsuppressible (S-100 LineInstructionUnsuppressed).
    /// Unsuppressed lines always render regardless of higher-priority lines
    /// on the same curve.
    #[inline]
    pub fn with_unsuppressed(mut self) -> Self {
        self.suppressible = false;
        self
    }

    #[inline]
    pub fn with_style_ref(mut self, style_ref: String) -> Self {
        self.style_ref = Some(style_ref);
        self
    }

    #[inline]
    pub fn with_style(mut self, style: LineStyle) -> Self {
        self.style = style;
        self
    }

    #[inline]
    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    /// Preserve every PC group; a disabled additional group disables this command.
    #[inline]
    pub fn with_viewing_groups(mut self, groups: &[u32]) -> Self {
        self.viewing_group = ViewingGroup(groups.first().copied().unwrap_or(21010));
        self.additional_viewing_groups = groups.iter().skip(1).copied().map(ViewingGroup).collect();
        self
    }

    #[inline]
    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self.additional_viewing_groups = Box::default();
        self
    }

    #[inline]
    pub fn with_cell_index(mut self, index: usize) -> Self {
        self.cell_index = Some(index as u32);
        self
    }

    #[inline]
    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }

    #[inline]
    pub fn with_scale_range(mut self, scale_range: ScaleRange) -> Self {
        self.scale_range = scale_range;
        self
    }

    #[inline]
    pub fn with_display_plane(mut self, display_plane: DisplayPlane) -> Self {
        self.display_plane = display_plane;
        self
    }
}

/// Area fill type
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AreaFillType {
    /// Solid color fill
    Solid(Color),
    /// Pattern fill (symbol reference) with parallelogram tiling vectors
    /// v1 and v2 define the lattice: each symbol is at origin + n*v1 + m*v2 (in mm)
    Pattern {
        symbol_ref: String,
        /// First lattice vector (mm). v1.y is always 0 in S-101 catalogues.
        v1: (f32, f32),
        /// Second lattice vector (mm). May have non-zero x for parallelogram tiling.
        v2: (f32, f32),
    },
    /// Hatch fill: parallel lines at a given angle (S-100 Part 9a)
    HatchFill {
        /// Line color
        color: Color,
        /// Line width in mm
        width: f32,
        /// Distance between parallel lines in mm
        spacing: f32,
        /// Direction angle in degrees (from the direction vector)
        angle: f32,
    },
    /// Centroid symbol only
    CentroidSymbol(String),
}

impl Default for AreaFillType {
    fn default() -> Self {
        AreaFillType::Solid(Color::TRANSPARENT)
    }
}

/// Area instruction - renders a filled polygon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AreaInstruction {
    /// Fill style reference ID (from PC) or inline fill
    pub fill_ref: Option<String>,
    /// Fill type
    pub fill: AreaFillType,
    /// Authored S-100 AreaCRS; retained independently of source geometry.
    #[serde(default)]
    pub pattern_crs: crate::PatternCrs,
    /// S-100 9a SymbolFill: true clips motifs at the area boundary; false
    /// requires complete motifs. Missing values use the normative true default.
    #[serde(default = "default_pattern_clip_symbols")]
    pub pattern_clip_symbols: bool,
    /// Both authored hatch line references in painter order. Product-neutral
    /// renderer resource resolution must not silently replace the second style.
    #[serde(default)]
    pub hatch_line_style_refs: Box<[String]>,
    /// Fully resolved ordered hatch strokes, including independent dash cycles.
    #[serde(default)]
    pub hatch_strokes: Box<[crate::HatchStroke]>,
    /// Authored alpha multiplier, separate from palette alpha.
    #[serde(default = "opaque_opacity")]
    pub fill_opacity: f32,
    /// Color token for solid fill remapping (e.g., "DEPVS", "LANDA")
    pub fill_color_token: Option<String>,
    /// Color token for hatch fill line color
    pub hatch_color_token: Option<String>,
    /// Exterior ring vertices
    pub exterior: Vec<WorldPoint>,
    /// Interior rings (holes)
    pub interiors: Vec<Vec<WorldPoint>>,
    /// Optional outline
    pub outline: Option<LineStyle>,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Additional groups are conjunctive under S-100 9-11.1.3.
    #[serde(default)]
    pub additional_viewing_groups: Box<[ViewingGroup]>,
    /// Scale-dependent visibility range
    pub scale_range: ScaleRange,
    /// Display plane (UnderRadar or OverRadar)
    pub display_plane: DisplayPlane,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
    /// Source cell identity; feature IDs are only unique within a cell.
    #[serde(default)]
    pub cell_index: Option<u32>,
    /// Accumulated S-100 time intervals; None means no temporal restriction.
    #[serde(default)]
    pub time_intervals: Option<Box<[ferrite_kernel::TemporalInterval]>>,
    #[serde(default)]
    pub dependency: Option<Box<crate::DrawingDependency>>,
    /// Source geometry for coverage visibility; independent of portrayal offsets.
    #[serde(default)]
    pub portrayal_origin: crate::PortrayalOrigin,
}

fn default_pattern_clip_symbols() -> bool {
    true
}

impl AreaInstruction {
    #[inline]
    pub fn with_pattern_clip_symbols(mut self, clip: bool) -> Self {
        self.pattern_clip_symbols = clip;
        self
    }

    #[inline]
    pub fn new(exterior: Vec<WorldPoint>) -> Self {
        AreaInstruction {
            fill_ref: None,
            fill: AreaFillType::default(),
            pattern_crs: crate::PatternCrs::default(),
            pattern_clip_symbols: true,
            hatch_line_style_refs: Box::default(),
            hatch_strokes: Box::default(),
            fill_opacity: 1.,
            fill_color_token: None,
            hatch_color_token: None,
            exterior,
            interiors: Vec::new(),
            outline: None,
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            additional_viewing_groups: Box::default(),
            scale_range: ScaleRange::default(),
            display_plane: DisplayPlane::default(),
            feature_id: None,
            cell_index: None,
            time_intervals: None,
            dependency: None,
            portrayal_origin: crate::PortrayalOrigin::Unspecified,
        }
    }

    pub fn with_pattern_crs(mut self, crs: crate::PatternCrs) -> Self {
        self.pattern_crs = crs;
        self
    }
    pub fn with_hatch_line_style_refs(mut self, refs: &[String]) -> Self {
        self.hatch_line_style_refs = refs.to_vec().into_boxed_slice();
        self
    }

    pub fn with_hatch_strokes(mut self, strokes: Vec<crate::HatchStroke>) -> Self {
        self.hatch_strokes = strokes.into_boxed_slice();
        self
    }

    #[inline]
    pub fn with_fill_ref(mut self, fill_ref: String) -> Self {
        self.fill_ref = Some(fill_ref);
        self
    }

    #[inline]
    pub fn with_solid_fill(mut self, color: Color) -> Self {
        self.fill = AreaFillType::Solid(color);
        self
    }

    #[inline]
    pub fn with_solid_fill_token(mut self, color: Color, token: &str) -> Self {
        self.fill = AreaFillType::Solid(color);
        self.fill_color_token = Some(token.to_string());
        self
    }

    /// Resolve palette alpha and retain the authored command opacity.
    pub fn with_solid_fill_token_opacity(
        mut self,
        color: Color,
        token: &str,
        opacity: f32,
    ) -> Self {
        self.fill = AreaFillType::Solid(color.with_alpha(opacity));
        self.fill_color_token = Some(token.into());
        self.fill_opacity = opacity;
        self
    }

    #[inline]
    pub fn with_pattern_fill(mut self, symbol_ref: String, v1: (f32, f32), v2: (f32, f32)) -> Self {
        self.fill = AreaFillType::Pattern { symbol_ref, v1, v2 };
        self
    }

    #[inline]
    pub fn with_hatch_fill(mut self, color: Color, width: f32, spacing: f32, angle: f32) -> Self {
        self.fill = AreaFillType::HatchFill {
            color,
            width,
            spacing,
            angle,
        };
        self
    }

    #[inline]
    pub fn with_hatch_fill_token(
        mut self,
        color: Color,
        token: &str,
        width: f32,
        spacing: f32,
        angle: f32,
    ) -> Self {
        self.fill = AreaFillType::HatchFill {
            color,
            width,
            spacing,
            angle,
        };
        self.hatch_color_token = Some(token.to_string());
        self
    }

    #[inline]
    pub fn with_interiors(mut self, interiors: Vec<Vec<WorldPoint>>) -> Self {
        self.interiors = interiors;
        self
    }

    #[inline]
    pub fn with_outline(mut self, style: LineStyle) -> Self {
        self.outline = Some(style);
        self
    }

    #[inline]
    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    /// Preserve every PC group; a disabled additional group disables this command.
    #[inline]
    pub fn with_viewing_groups(mut self, groups: &[u32]) -> Self {
        self.viewing_group = ViewingGroup(groups.first().copied().unwrap_or(21010));
        self.additional_viewing_groups = groups.iter().skip(1).copied().map(ViewingGroup).collect();
        self
    }

    #[inline]
    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self.additional_viewing_groups = Box::default();
        self
    }

    #[inline]
    pub fn with_cell_index(mut self, index: usize) -> Self {
        self.cell_index = Some(index as u32);
        self
    }

    #[inline]
    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }

    #[inline]
    pub fn with_scale_range(mut self, scale_range: ScaleRange) -> Self {
        self.scale_range = scale_range;
        self
    }

    #[inline]
    pub fn with_display_plane(mut self, display_plane: DisplayPlane) -> Self {
        self.display_plane = display_plane;
        self
    }
}

/// Text instruction - renders text label
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TextInstruction {
    /// Text content
    pub text: String,
    /// Position in world coordinates
    pub position: WorldPoint,
    /// Font size in points
    pub font_size: f32,
    /// Font family (optional)
    pub font_family: Option<String>,
    /// Font weight (bold)
    pub bold: bool,
    /// Font style (italic)
    pub italic: bool,
    /// Text color
    pub color: Color,
    #[serde(default = "opaque_opacity")]
    pub color_opacity: f32,
    /// Color token for text color remapping
    pub color_token: Option<String>,
    /// Background color (None = transparent)
    pub background: Option<Color>,
    #[serde(default)]
    pub background_color_token: Option<String>,
    #[serde(default = "opaque_opacity")]
    pub background_opacity: f32,
    /// Horizontal alignment
    pub h_align: HAlign,
    /// Vertical alignment
    pub v_align: VAlign,
    /// Clockwise degrees in the authored S-100 rotation basis.
    pub rotation: f32,
    #[serde(default)]
    pub rotation_crs: crate::RotationCrs,
    /// Authored source curve tangent, when placement supplies one.
    #[serde(default)]
    pub curve_tangent_bearing: Option<f64>,
    /// LocalOffset in millimetres (positive y upwards).
    pub offset: ScreenPoint,
    /// Display priority
    pub priority: DisplayPriority,
    /// Viewing group
    pub viewing_group: ViewingGroup,
    /// Additional groups are conjunctive under S-100 9-11.1.3.
    #[serde(default)]
    pub additional_viewing_groups: Box<[ViewingGroup]>,
    /// Scale-dependent visibility range
    pub scale_range: ScaleRange,
    /// Display plane (UnderRadar or OverRadar)
    pub display_plane: DisplayPlane,
    /// Feature ID this instruction belongs to
    pub feature_id: Option<i64>,
    /// Source cell identity; feature IDs are only unique within a cell.
    #[serde(default)]
    pub cell_index: Option<u32>,
    /// Accumulated S-100 time intervals; None means no temporal restriction.
    #[serde(default)]
    pub time_intervals: Option<Box<[ferrite_kernel::TemporalInterval]>>,
    #[serde(default)]
    pub dependency: Option<Box<crate::DrawingDependency>>,
    /// Source geometry for coverage visibility; independent of portrayal offsets.
    #[serde(default)]
    pub portrayal_origin: crate::PortrayalOrigin,
}

impl TextInstruction {
    #[inline]
    pub fn new(text: String, position: WorldPoint) -> Self {
        TextInstruction {
            text,
            position,
            font_size: 10.0,
            font_family: None,
            bold: false,
            italic: false,
            color: Color::BLACK,
            color_opacity: 1.,
            background: None,
            background_color_token: None,
            background_opacity: 1.,
            h_align: HAlign::Left,
            v_align: VAlign::Middle,
            rotation: 0.0,
            rotation_crs: crate::RotationCrs::Portrayal,
            curve_tangent_bearing: None,
            offset: ScreenPoint::zero(),
            priority: DisplayPriority::default(),
            viewing_group: ViewingGroup::default(),
            additional_viewing_groups: Box::default(),
            scale_range: ScaleRange::default(),
            display_plane: DisplayPlane::default(),
            feature_id: None,
            cell_index: None,
            time_intervals: None,
            dependency: None,
            portrayal_origin: crate::PortrayalOrigin::Unspecified,
            color_token: None,
        }
    }

    #[inline]
    pub fn with_font_size(mut self, size: f32) -> Self {
        self.font_size = size;
        self
    }

    #[inline]
    pub fn with_color(mut self, color: Color) -> Self {
        self.color = color;
        self
    }

    pub fn with_color_token_opacity(mut self, color: Color, token: &str, opacity: f32) -> Self {
        self.color = color.with_alpha(opacity);
        self.color_token = Some(token.into());
        self.color_opacity = opacity;
        self
    }

    pub fn with_background_token_opacity(
        mut self,
        color: Color,
        token: &str,
        opacity: f32,
    ) -> Self {
        self.background = Some(color.with_alpha(opacity));
        self.background_color_token = Some(token.into());
        self.background_opacity = opacity;
        self
    }

    /// Invisible text must not reserve space in the decluttering index.
    pub fn has_visible_content(&self) -> bool {
        // An empty label has no glyphs or nonzero background extent. Counting
        // it as an executed parent would incorrectly enable dependent marks.
        if self.text.is_empty() {
            return false;
        }
        let visible = |c: Color| c.a.is_finite() && c.a > 0.;
        visible(self.color) || self.background.is_some_and(visible)
    }

    #[inline]
    pub fn with_alignment(mut self, h: HAlign, v: VAlign) -> Self {
        self.h_align = h;
        self.v_align = v;
        self
    }

    #[inline]
    pub fn with_rotation(mut self, degrees: f32) -> Self {
        self.rotation = degrees;
        self
    }

    pub fn with_rotation_crs(mut self, crs: crate::RotationCrs) -> Self {
        self.rotation_crs = crs;
        self
    }
    pub fn with_curve_tangent(mut self, bearing: Option<f64>) -> Self {
        self.curve_tangent_bearing = bearing;
        self
    }
    #[inline]
    pub fn with_offset(mut self, x: f32, y: f32) -> Self {
        self.offset = ScreenPoint::new(x, y);
        self
    }

    #[inline]
    pub fn with_priority(mut self, priority: i32) -> Self {
        self.priority = DisplayPriority(priority);
        self
    }

    /// Preserve every PC group; a disabled additional group disables this command.
    #[inline]
    pub fn with_viewing_groups(mut self, groups: &[u32]) -> Self {
        self.viewing_group = ViewingGroup(groups.first().copied().unwrap_or(21010));
        self.additional_viewing_groups = groups.iter().skip(1).copied().map(ViewingGroup).collect();
        self
    }

    #[inline]
    pub fn with_viewing_group(mut self, vg: u32) -> Self {
        self.viewing_group = ViewingGroup(vg);
        self.additional_viewing_groups = Box::default();
        self
    }

    #[inline]
    pub fn with_cell_index(mut self, index: usize) -> Self {
        self.cell_index = Some(index as u32);
        self
    }

    #[inline]
    pub fn with_feature_id(mut self, id: i64) -> Self {
        self.feature_id = Some(id);
        self
    }

    #[inline]
    pub fn with_scale_range(mut self, scale_range: ScaleRange) -> Self {
        self.scale_range = scale_range;
        self
    }

    #[inline]
    pub fn with_display_plane(mut self, display_plane: DisplayPlane) -> Self {
        self.display_plane = display_plane;
        self
    }
}

/// All drawing instruction types
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DrawingInstruction {
    Point(PointInstruction),
    Line(LineInstruction),
    Area(AreaInstruction),
    Text(TextInstruction),
}

impl DrawingInstruction {
    pub fn portrayal_origin(&self) -> &crate::PortrayalOrigin {
        match self {
            Self::Point(i) => &i.portrayal_origin,
            Self::Line(i) => &i.portrayal_origin,
            Self::Area(i) => &i.portrayal_origin,
            Self::Text(i) => &i.portrayal_origin,
        }
    }
    pub fn set_portrayal_origin(&mut self, origin: crate::PortrayalOrigin) {
        match self {
            Self::Point(i) => i.portrayal_origin = origin,
            Self::Line(i) => i.portrayal_origin = origin,
            Self::Area(i) => i.portrayal_origin = origin,
            Self::Text(i) => i.portrayal_origin = origin,
        }
    }

    /// Apply a validated composition plan without changing geometry, scale or temporal visibility.
    pub fn set_display_parameters(
        &mut self,
        plane: DisplayPlane,
        priority: i32,
        viewing_group: u32,
    ) {
        match self {
            Self::Point(i) => {
                i.display_plane = plane;
                i.priority = DisplayPriority(priority);
                i.viewing_group = ViewingGroup(viewing_group);
                i.additional_viewing_groups = Box::default();
            }
            Self::Line(i) => {
                i.display_plane = plane;
                i.priority = DisplayPriority(priority);
                i.viewing_group = ViewingGroup(viewing_group);
                i.additional_viewing_groups = Box::default();
            }
            Self::Area(i) => {
                i.display_plane = plane;
                i.priority = DisplayPriority(priority);
                i.viewing_group = ViewingGroup(viewing_group);
                i.additional_viewing_groups = Box::default();
            }
            Self::Text(i) => {
                i.display_plane = plane;
                i.priority = DisplayPriority(priority);
                i.viewing_group = ViewingGroup(viewing_group);
                i.additional_viewing_groups = Box::default();
            }
        }
    }
    pub fn cell_index(&self) -> Option<u32> {
        match self {
            Self::Point(i) => i.cell_index,
            Self::Line(i) => i.cell_index,
            Self::Area(i) => i.cell_index,
            Self::Text(i) => i.cell_index,
        }
    }

    pub fn priority(&self) -> DisplayPriority {
        match self {
            DrawingInstruction::Point(i) => i.priority,
            DrawingInstruction::Line(i) => i.priority,
            DrawingInstruction::Area(i) => i.priority,
            DrawingInstruction::Text(i) => i.priority,
        }
    }

    pub fn viewing_group(&self) -> ViewingGroup {
        match self {
            DrawingInstruction::Point(i) => i.viewing_group,
            DrawingInstruction::Line(i) => i.viewing_group,
            DrawingInstruction::Area(i) => i.viewing_group,
            DrawingInstruction::Text(i) => i.viewing_group,
        }
    }

    /// Iteration is allocation-free for both single and multiple viewing groups.
    pub fn viewing_groups(&self) -> impl Iterator<Item = ViewingGroup> + '_ {
        let extra = match self {
            Self::Point(i) => &i.additional_viewing_groups,
            Self::Line(i) => &i.additional_viewing_groups,
            Self::Area(i) => &i.additional_viewing_groups,
            Self::Text(i) => &i.additional_viewing_groups,
        };
        std::iter::once(self.viewing_group()).chain(extra.iter().copied())
    }

    pub fn time_intervals(&self) -> &[ferrite_kernel::TemporalInterval] {
        match self {
            Self::Point(i) => i.time_intervals.as_deref(),
            Self::Line(i) => i.time_intervals.as_deref(),
            Self::Area(i) => i.time_intervals.as_deref(),
            Self::Text(i) => i.time_intervals.as_deref(),
        }
        .unwrap_or(&[])
    }

    pub fn dependency(&self) -> Option<&crate::DrawingDependency> {
        match self {
            Self::Point(i) => i.dependency.as_deref(),
            Self::Line(i) => i.dependency.as_deref(),
            Self::Area(i) => i.dependency.as_deref(),
            Self::Text(i) => i.dependency.as_deref(),
        }
    }
    pub fn set_dependency(&mut self, dependency: Option<crate::DrawingDependency>) {
        let value = dependency.map(Box::new);
        match self {
            Self::Point(i) => i.dependency = value,
            Self::Line(i) => i.dependency = value,
            Self::Area(i) => i.dependency = value,
            Self::Text(i) => i.dependency = value,
        }
    }

    pub fn set_time_intervals(&mut self, intervals: &[ferrite_kernel::TemporalInterval]) {
        let value = if intervals.is_empty() {
            None
        } else {
            Some(intervals.into())
        };
        match self {
            Self::Point(i) => i.time_intervals = value,
            Self::Line(i) => i.time_intervals = value,
            Self::Area(i) => i.time_intervals = value,
            Self::Text(i) => i.time_intervals = value,
        }
    }

    pub fn feature_id(&self) -> Option<i64> {
        match self {
            DrawingInstruction::Point(i) => i.feature_id,
            DrawingInstruction::Line(i) => i.feature_id,
            DrawingInstruction::Area(i) => i.feature_id,
            DrawingInstruction::Text(i) => i.feature_id,
        }
    }

    pub fn scale_range(&self) -> ScaleRange {
        match self {
            DrawingInstruction::Point(i) => i.scale_range,
            DrawingInstruction::Line(i) => i.scale_range,
            DrawingInstruction::Area(i) => i.scale_range,
            DrawingInstruction::Text(i) => i.scale_range,
        }
    }

    pub fn display_plane(&self) -> DisplayPlane {
        match self {
            DrawingInstruction::Point(i) => i.display_plane,
            DrawingInstruction::Line(i) => i.display_plane,
            DrawingInstruction::Area(i) => i.display_plane,
            DrawingInstruction::Text(i) => i.display_plane,
        }
    }

    /// Get geometry type for S-101 render ordering
    pub fn geometry_type(&self) -> GeometryType {
        match self {
            DrawingInstruction::Area(_) => GeometryType::Area,
            DrawingInstruction::Line(_) => GeometryType::Line,
            DrawingInstruction::Point(_) => GeometryType::Point,
            DrawingInstruction::Text(_) => GeometryType::Text,
        }
    }

    /// Get S-101 compliant render order key
    /// Used for sorting: lower values rendered first (background)
    pub fn render_order(&self) -> RenderOrder {
        let order = RenderOrder::new(self.priority(), self.geometry_type(), self.feature_id())
            .with_render_category(self.viewing_group().0);
        // For area features, sort by bounding box extent (larger areas first = background)
        if let DrawingInstruction::Area(area) = self {
            let (mut x0, mut y0, mut x1, mut y1) = (f64::MAX, f64::MAX, f64::MIN, f64::MIN);
            for p in &area.exterior {
                if p.x < x0 {
                    x0 = p.x;
                }
                if p.y < y0 {
                    y0 = p.y;
                }
                if p.x > x1 {
                    x1 = p.x;
                }
                if p.y > y1 {
                    y1 = p.y;
                }
            }
            let extent = (x1 - x0) * (y1 - y0);
            return order.with_extent(extent);
        }
        order
    }

    /// Remap resolved colors using a token-to-color lookup function.
    /// Used for color profile switch (Day/Dusk/Night) without re-running Lua.
    pub fn remap_colors(&mut self, lookup: &dyn Fn(&str) -> Color) {
        match self {
            DrawingInstruction::Area(area) => {
                if let Some(token) = &area.fill_color_token {
                    if let AreaFillType::Solid(ref mut color) = area.fill {
                        *color = lookup(token).with_alpha(area.fill_opacity);
                    }
                }
                if let Some(token) = &area.hatch_color_token {
                    if let AreaFillType::HatchFill { ref mut color, .. } = area.fill {
                        *color = lookup(token).with_alpha(area.fill_opacity);
                    }
                }
                for stroke in &mut area.hatch_strokes {
                    if let Some(token) = &stroke.style.color_token {
                        stroke.style.color = lookup(token).with_alpha(stroke.style.opacity);
                    }
                }
                if let Some(ref mut outline) = area.outline {
                    if let Some(token) = &outline.color_token {
                        outline.color = lookup(token);
                        outline.color.a *= outline.opacity;
                    }
                }
            }
            DrawingInstruction::Line(line) => {
                if let Some(token) = &line.color_token {
                    line.style.color = lookup(token);
                    line.style.color.a *= line.style.opacity;
                }
            }
            DrawingInstruction::Text(text) => {
                if let Some(token) = &text.color_token {
                    text.color = lookup(token).with_alpha(text.color_opacity);
                }
                if let Some(token) = &text.background_color_token {
                    text.background = Some(lookup(token).with_alpha(text.background_opacity));
                }
            }
            DrawingInstruction::Point(_) => {
                // Point symbols use SVG rendering with color overrides;
                // handled by clearing symbol_cache on profile switch
            }
        }
    }
}

/// Collection of drawing instructions for a feature
#[derive(Debug, Clone, Default)]
pub struct FeatureInstructions {
    pub instructions: Vec<DrawingInstruction>,
}

impl FeatureInstructions {
    pub fn new() -> Self {
        FeatureInstructions {
            instructions: Vec::new(),
        }
    }

    pub fn add_point(&mut self, instruction: PointInstruction) {
        self.instructions
            .push(DrawingInstruction::Point(instruction));
    }

    pub fn add_line(&mut self, instruction: LineInstruction) {
        self.instructions
            .push(DrawingInstruction::Line(instruction));
    }

    pub fn add_area(&mut self, instruction: AreaInstruction) {
        self.instructions
            .push(DrawingInstruction::Area(instruction));
    }

    pub fn add_text(&mut self, instruction: TextInstruction) {
        self.instructions
            .push(DrawingInstruction::Text(instruction));
    }

    pub fn is_empty(&self) -> bool {
        self.instructions.is_empty()
    }

    pub fn len(&self) -> usize {
        self.instructions.len()
    }

    /// Sort by display priority
    pub fn sort_by_priority(&mut self) {
        self.instructions.sort_by_key(|i| i.priority());
    }
}

#[cfg(test)]
mod stroke_unit_tests {
    use super::*;
    #[test]
    fn portrayal_width_respects_display_density_and_legacy_pixels() {
        let mm = LineStyle::solid_mm(Color::BLACK, 0.32);
        let one = mm.physical_width(96.0 / 25.4);
        assert!((one - 1.2094488).abs() < 1e-6);
        assert_eq!(mm.physical_width(192.0 / 25.4), 2.0 * one);
        assert_eq!(
            LineStyle::solid(Color::BLACK, 4.0).physical_width(192.0 / 25.4),
            4.0
        );
        let roundtrip: LineStyle =
            serde_json::from_str(&serde_json::to_string(&mm).unwrap()).unwrap();
        assert_eq!(roundtrip.width_unit, StrokeUnit::Millimetres);
        let mut legacy = serde_json::to_value(LineStyle::default()).unwrap();
        legacy.as_object_mut().unwrap().remove("width_unit");
        let legacy: LineStyle = serde_json::from_value(legacy).unwrap();
        assert_eq!(legacy.width_unit, StrokeUnit::PhysicalPixels);
    }
    #[test]
    fn invalid_width_emits_no_stroke() {
        for width in [0.0, -1.0, f32::NAN, f32::INFINITY] {
            assert_eq!(
                LineStyle::solid_mm(Color::BLACK, width).physical_width(4.0),
                0.0
            );
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ScreenRay {
    pub direction: f64,
    pub length_mm: f64,
    pub geographic_direction: bool,
}
/// Ordinary world lines borrow their original points without heap allocation.
pub enum ResolvedLinePaths<'a> {
    Single(Option<std::borrow::Cow<'a, [WorldPoint]>>),
    Multiple(std::vec::IntoIter<Vec<WorldPoint>>),
}
impl<'a> Iterator for ResolvedLinePaths<'a> {
    type Item = std::borrow::Cow<'a, [WorldPoint]>;
    fn next(&mut self) -> Option<Self::Item> {
        match self {
            Self::Single(p) => p.take(),
            Self::Multiple(p) => p.next().map(std::borrow::Cow::Owned),
        }
    }
}
impl LineInstruction {
    pub fn render_paths<'a>(&'a self, scaler: &crate::Scaler) -> ResolvedLinePaths<'a> {
        if let (Some(path @ crate::PortrayalPath::Group(_)), Some(&origin)) =
            (&self.portrayal_path, self.points.first())
        {
            ResolvedLinePaths::Multiple(path.world_paths(origin, scaler).into_iter())
        } else {
            ResolvedLinePaths::Single(Some(self.render_points(scaler)))
        }
    }
    pub fn render_points<'a>(
        &'a self,
        scaler: &crate::Scaler,
    ) -> std::borrow::Cow<'a, [WorldPoint]> {
        if let (Some(path), Some(&origin)) = (&self.portrayal_path, self.points.first()) {
            return std::borrow::Cow::Owned(path.world_points(origin, scaler));
        }
        let Some(ray) = self.screen_ray else {
            return std::borrow::Cow::Borrowed(&self.points);
        };
        let Some(&origin) = self.points.first() else {
            return std::borrow::Cow::Borrowed(&self.points);
        };
        if !ray.direction.is_finite() || !ray.length_mm.is_finite() || ray.length_mm < 0. {
            return std::borrow::Cow::Borrowed(&[]);
        }
        let angle = ray.direction.to_radians();
        let (mut dx, mut dy) = (angle.sin(), -angle.cos());
        if ray.geographic_direction && scaler.projection() == crate::FlatProjection::LocalGeographic
        {
            dx = dx
                / scaler
                    .geo_bounds
                    .center()
                    .y
                    .to_radians()
                    .cos()
                    .abs()
                    .max(1e-6)
                * scaler.scale_x();
            dy *= scaler.scale_y();
            let norm = dx.hypot(dy);
            dx /= norm;
            dy /= norm;
        }
        let start = scaler.world_to_screen(origin);
        let length = ray.length_mm * scaler.pixels_per_mm();
        let end = scaler.screen_to_world(crate::ScreenPoint::new(
            start.x + (dx * length) as f32,
            start.y + (dy * length) as f32,
        ));
        std::borrow::Cow::Owned(vec![origin, end])
    }
}

#[cfg(test)]
mod authored_opacity_tests {
    use super::*;
    #[test]
    fn palette_switch_preserves_authored_fill_glyph_and_background_alpha() {
        let mut area = DrawingInstruction::Area(
            AreaInstruction::new(vec![]).with_solid_fill_token_opacity(Color::RED, "FILL", 0.5),
        );
        let mut text = DrawingInstruction::Text(
            TextInstruction::new("label".into(), WorldPoint::new(0., 0.))
                .with_color_token_opacity(Color::BLACK, "GLYPH", 0.25)
                .with_background_token_opacity(Color::WHITE, "BG", 0.75),
        );
        for rgb in [Color::BLUE, Color::GREEN, Color::RED] {
            let lookup = |_: &str| rgb.with_alpha(0.8);
            area.remap_colors(&lookup);
            text.remap_colors(&lookup);
            let DrawingInstruction::Area(a) = &area else {
                panic!()
            };
            let AreaFillType::Solid(c) = a.fill else {
                panic!()
            };
            assert!((c.a - 0.4).abs() < 1e-6);
            let DrawingInstruction::Text(t) = &text else {
                panic!()
            };
            assert!((t.color.a - 0.2).abs() < 1e-6);
            assert!((t.background.unwrap().a - 0.6).abs() < 1e-6);
            assert_eq!(t.color.r, rgb.r);
        }
        // A cache round-trip must retain command opacity, not just current alpha.
        let mut restored: DrawingInstruction =
            serde_json::from_str(&serde_json::to_string(&text).unwrap()).unwrap();
        restored.remap_colors(&|_| Color::WHITE);
        let DrawingInstruction::Text(t) = restored else {
            panic!()
        };
        assert_eq!(t.color.a, 0.25);
        assert_eq!(t.background.unwrap().a, 0.75);
    }
    #[test]
    fn transparent_glyphs_with_visible_background_are_visible_but_empty_alpha_is_not() {
        let mut t = TextInstruction::new("label".into(), WorldPoint::new(0., 0.))
            .with_color(Color::TRANSPARENT);
        assert!(!t.has_visible_content());
        t.background = Some(Color::RED.with_alpha(0.5));
        assert!(t.has_visible_content());
        t.background = Some(Color::TRANSPARENT);
        assert!(!t.has_visible_content());
        t.color.a = f32::NAN;
        assert!(!t.has_visible_content());
    }
}

#[cfg(test)]
mod interop_plane_tests {
    use super::*;
    #[test]
    fn signed_planes_preserve_full_order_and_reject_radar_zero() {
        let p = |n| DisplayPlane::Interoperability(std::num::NonZeroI32::new(n).unwrap());
        assert!(
            p(-10000).composition_plane(ferrite_kernel::CompositionStage::Chart)
                < p(-500).composition_plane(ferrite_kernel::CompositionStage::Chart)
        );
        assert!(p(-500).order() < p(10000).order());
        assert!(serde_json::from_str::<DisplayPlane>(r#"{"Interoperability":0}"#).is_err());
        let plane = p(i32::MIN);
        assert_eq!(
            serde_json::from_str::<DisplayPlane>(&serde_json::to_string(&plane).unwrap()).unwrap(),
            plane
        );
        assert!(
            DisplayPlane::OverRadar.composition_plane(ferrite_kernel::CompositionStage::Chart)
                < DisplayPlane::UnderRadar
                    .composition_plane(ferrite_kernel::CompositionStage::Overlay)
        );
    }
}

#[cfg(test)]
mod multiple_group_tests {
    use super::*;
    use std::collections::HashSet;
    #[test]
    fn every_instruction_requires_all_groups_and_ic_replaces_them() {
        let p = WorldPoint::new(0., 0.);
        let items = [
            DrawingInstruction::Point(
                PointInstruction::new("X".into(), p).with_viewing_groups(&[27070, 90020]),
            ),
            DrawingInstruction::Line(
                LineInstruction::new(vec![p, WorldPoint::new(1., 1.)])
                    .with_viewing_groups(&[27070, 90020]),
            ),
            DrawingInstruction::Area(
                AreaInstruction::new(vec![p, WorldPoint::new(1., 0.), WorldPoint::new(1., 1.)])
                    .with_viewing_groups(&[27070, 90020]),
            ),
            DrawingInstruction::Text(
                TextInstruction::new("X".into(), p).with_viewing_groups(&[27070, 90020]),
            ),
        ];
        let primary = HashSet::from([27070]);
        let both = HashSet::from([27070, 90020]);
        for item in items {
            assert_eq!(
                item.viewing_groups().map(|g| g.0).collect::<Vec<_>>(),
                [27070, 90020]
            );
            assert!(crate::instruction_visible(&item, 1000, Some(&both), None));
            assert!(!crate::instruction_visible(
                &item,
                1000,
                Some(&primary),
                None
            ));
            assert!(!crate::instruction_visible(
                &item,
                1000,
                Some(&HashSet::new()),
                Some(27070)
            ));
            let bytes = bincode::serialize(&item).unwrap();
            let mut restored: DrawingInstruction = bincode::deserialize(&bytes).unwrap();
            assert_eq!(
                restored.viewing_groups().map(|g| g.0).collect::<Vec<_>>(),
                [27070, 90020]
            );
            let mut context = crate::RenderContext::new(crate::Viewport::new(100., 100.));
            context.viewing_groups.set_visible(90020, false);
            context.add_instruction(item);
            assert_eq!(context.instruction_count(), 0);
            restored.set_display_parameters(DisplayPlane::UnderRadar, 5, 11010);
            assert_eq!(
                restored.viewing_groups().map(|g| g.0).collect::<Vec<_>>(),
                [11010]
            );
        }
    }
}

#[cfg(test)]
mod empty_text_tests {
    use super::*;
    #[test]
    fn empty_text_has_no_executable_glyph_or_background_extent() {
        let mut label = TextInstruction::new(String::new(), WorldPoint::new(0., 0.));
        assert!(!label.has_visible_content());
        label.background = Some(Color::RED);
        assert!(!label.has_visible_content());
        label.text = "label".into();
        assert!(label.has_visible_content());
    }
}

#[cfg(test)]
mod catalogue_plane_tests {
    use super::*;
    #[test]
    fn catalogue_plane_orders_share_composition_sorting_and_roundtrip_without_truncation() {
        let mut planes = Vec::new();
        for value in [i32::MIN, -701, -1, 1, 90000, i32::MAX] {
            let p = DisplayPlane::from_catalogue_order(std::num::NonZeroI32::new(value).unwrap());
            assert_eq!(p.order().get(), value);
            let restored: DisplayPlane =
                serde_json::from_str(&serde_json::to_string(&p).unwrap()).unwrap();
            assert_eq!(restored, p);
            assert_eq!(
                p.composition_plane(ferrite_kernel::CompositionStage::Chart),
                DisplayPlane::Interoperability(p.order())
                    .composition_plane(ferrite_kernel::CompositionStage::Chart)
            );
            planes.push(p.composition_plane(ferrite_kernel::CompositionStage::Chart));
        }
        assert!(planes.windows(2).all(|p| p[0] < p[1]));
        assert!(serde_json::from_str::<DisplayPlane>(r#"{"Catalogue":0}"#).is_err());
    }
}
